version: "3.9"

services:
  # Laravel App
  app:
    build:
      context: ./backend
      dockerfile: php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - laravel
    depends_on:
      - mariadb
      - redis
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=mariadb"
      - "DB_PORT=3306"
      - "DB_DATABASE=${DB_DATABASE:-laravel}"
      - "DB_USERNAME=${DB_USERNAME:-laravel}"
      - "DB_PASSWORD=${DB_PASSWORD:-secret}"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "APP_KEY=${APP_KEY:-laravel}"
      - "FONT_END_BASE=${FONT_END_BASE:-http://localhost:3001/api/revalidate}"
      - "APP_DEBUG=${APP_DEBUG:-true}"

  # Nginx
  nginx:
    image: nginx:1.25-alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./backend/:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  # MariaDB
  mariadb:
    image: mariadb:11
    container_name: laravel_mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - laravel

  # Redis
  redis:
    image: redis:7-alpine
    container_name: laravel_redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - laravel

  # Frontend Next.js
  next:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${NEXT_ENV:-dev}   # dev | prod
    container_name: nextjs
    ports:
      - "${NEXT_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - laravel
    environment:
      - NODE_ENV=${NEXT_ENV:-development}
      - BASE_URL=${BASE_URL:-http://nginx/api/}
      - REVALIDATION_TOKEN=${REVALIDATION_TOKEN:-'N0Sug@r'}
    depends_on:
      - nginx
    command: ["npm","run","dev","--","-H","0.0.0.0","-p","3000"]

  # Admin Next.js
  adminfromt:
    build:
      context: ./admin
      dockerfile: Dockerfile
      target: ${NEXT_ENV:-dev}   # dev | prod
    container_name: admin
    ports:
      - "${NEXT_ADMIN_PORT:-3001}:3001"
    volumes:
      - ./admin:/app
      - /app/node_modules
    networks:
      - laravel
    environment:
      - NODE_ENV=${NEXT_ENV:-development}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://nginx/api/}
      - REVALIDATION_TOKEN=${REVALIDATION_TOKEN:-'N0Sug@r'}
    depends_on:
      - nginx
    command: ["npm","run","dev","--","-H","0.0.0.0","-p","3001"]

volumes:
  mariadb_data:
  redis_data:

networks:
  laravel:
